apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
#        envFrom:
 #        - secretRef:
  #           name: mysecret
        imagePullPolicy: Always
        image: hritikchaudhary/demo:order
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 600m
   #   imagePullSecrets:
    #  - name: order
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysecret
#type: Opaque
#stringData:
#    REDIS_DB_PORT : "6379"
#    REDIS_DB_URL : http://redis-master
#    MONGODB_DB_URL : mongodb://mongo:27017/users
