apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: api-gateway
        envFrom:
         - secretRef:
             name: product
        imagePullPolicy: Always
        image: hritikchaudhary/demo:product
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 600m
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
    REDIS_DB_PORT : "6379"
    REDIS_DB_URL : http://redis-master
    MONGODB_DB_URL : mongodb://mongo:27017/users
